Change return types in api
jczornik/JiraClient pull request #10
Opened 2021-06-29 17:43 UTC by jczornik

Return types are messed up in public API. This PR should fix it.

2021-06-29 18:26 UTC, jczornik reviewed
Issues to fix before merge

2021-06-29 18:26 UTC, jczornik commented on Sources/JiraClient/Clients/BaseClient/ResultDataSource.swift
>      /// - Returns: Internal response object
Return type in the comment does not correspond to the actual return type

2021-06-29 18:26 UTC, jczornik commented on Sources/JiraClient/Clients/BaseClient/ResultDataSource.swift
>      /// - Returns: Internal response object
Return type in the comment does not correspond to the actual return type

2021-06-29 18:26 UTC, jczornik commented on Sources/JiraClient/ResponseHandlers/OkResponseHandler.swift
>      ///     - If cannot parse response body will return .failure(.CannotParseResponse)
Return type in the comment does not correspond to the actual return type

2021-06-29 18:26 UTC, jczornik commented on Sources/JiraClient/ResponseHandlers/UnauthorisedResponseHandler.swift
>      ///     - If cannot parse response body will return .failure(.CannotParseResponse)
Return type in the comment does not correspond to the actual return type

2021-06-29 18:26 UTC, jczornik commented on Tests/JiraClientTests/Mocks/ServerRequesting/ServerRequestingDummy.swift
>          }
This should not be empty

2021-06-29 18:26 UTC, jczornik commented on Tests/JiraClientTests/ResponseHandlers/UnauthorizedResponseHandlerTests.swift
>          }
This can be simplified

2021-06-29 18:38 UTC, travnick requested changes
review done

2021-06-29 18:38 UTC, travnick commented on Sources/JiraClient/Clients/BaseClient/ResultDataSource.swift
> +/// Parsed server response
add here more comments please

2021-06-30 04:14 UTC, jczornik commented on Sources/JiraClient/Clients/BaseClient/ResultDataSource.swift
>      /// - Returns: Internal response object
Fixed

2021-06-30 04:14 UTC, jczornik commented on Sources/JiraClient/ResponseHandlers/OkResponseHandler.swift
>      ///     - If cannot parse response body will return .failure(.CannotParseResponse)
Fixed

2021-06-30 04:14 UTC, jczornik commented on Sources/JiraClient/Clients/BaseClient/ResultDataSource.swift
>      /// - Returns: Internal response object
Fixed

2021-06-30 04:15 UTC, jczornik commented on Sources/JiraClient/ResponseHandlers/UnauthorisedResponseHandler.swift
>      ///     - If cannot parse response body will return .failure(.CannotParseResponse)
Fixed

2021-06-30 04:15 UTC, jczornik commented on Sources/JiraClient/Clients/BaseClient/ResultDataSource.swift
> +/// Parsed server response
Fixed

2021-07-18 10:39 UTC, merged